### ISSUE TITLE
Jooq excute jar

### ISSUE THREAD

**Issue by Ivra23** [RWTH-i5-IDSG/steve#153]
Hello,
You can help me because I find the solution to my problem but that doesn't resolve itself, 
I found that it was a problem of logo but in the file log4j2.xml tthis line 
fix this problem 
**https://github.com/jOOQ/jOOQ/ issues / 4019
<AsyncLogger name = "org.jooq.Constants" level = "WARN" />**

![image](https://user-images.githubusercontent.com/38098276/60439896-ec0b8380-9c13-11e9-8c11-5c4882774ba8.png)

But in excute programm it persists.

Thank you

**Comment by goekay** [comment]
sorry but i don't understand what the problem is. here are a couple of things:
- jooq logo is not a problem. i don't know why you bring it up.
- the warnings from the screenshot are not a problem. they do not cause the fail.
- as the last log line mentions, please take a look at the log file and find the exception for the actual reason of the problem.

**Comment by Ivra23** [comment]
okeay sorry for the inconvenience, 
I will delete my issues :)
