### ISSUE TITLE
dataTransfer Implementation

### ISSUE THREAD

**Issue by eviontech** [RWTH-i5-IDSG/steve#263]
Is there any database table where messages from datatransfer are getting saved

if not how to modify it to save to an database table

**Comment by goekay** [comment]
data transfer messages are not saved to the database. steve only has a dummy implementation of this feature, since it will probably be vendor-specific. if you need to modify the implementation (to save it to database or whatever), [this is the place in code](https://github.com/RWTH-i5-IDSG/steve/blob/master/src/main/java/de/rwth/idsg/steve/service/CentralSystemService16_Service.java#L243-L257), where it's handled.
