### ISSUE TITLE
Don't function with plus symbol in chargebox id

### ISSUE THREAD

**Issue by patudd** [RWTH-i5-IDSG/steve#5]
for example "+49*861*0125*0013", issues in Chargebox Details because ajax mistake?

**Comment by goRaspy** [comment]
Just tried without problem wth my case. Could you post log files ?

**Comment by goekay** [comment]
Well, it is indeed a problem due to the special character handling of "+" in URLs, since it means whitespace. Therefore, in Ajax calls the the "+" in chargeboxId is replaced with whitespace, and a DB query with " 498610125*0013" does not return anything.

I fixed the problem and it works as expected. I will commit the changes today. Thanks.
