### ISSUE TITLE
Missing many @Override annotations, also name shadowing

### ISSUE THREAD

**Issue by evanbross** [RWTH-i5-IDSG/steve#669]
#### Checklist

- [x] I checked other issues already and found no answer
- [x] I checked the documentation and found no answer
- [x] I am running the latest version and the feature i am requesting is not implemented there

#### Describe the problem you are trying to solve

My group has very strict rules about java warnings & safety, based on past problems.
Missing @Override annotations and name shadowing are flagged as errors to prevent problems from creeping in during SDLC
...

#### Describe the solution you'd like

...

#### Describe alternative solutions or features you've considered 

...

#### Additional context

...

**Comment by goekay** [comment]
can you give code examples for these issues? or better: please make a PR that addresses these issues. we would welcome that!

**Comment by evanbross** [comment]
I'm always reluctant to add things back to an open source repo since my
java formatter may not agree with the existing format

**Comment by goekay** [comment]
hey, i am making a general code refactoring round in [code_refactor](https://github.com/RWTH-i5-IDSG/steve/commits/code_refactor) branch. however, i am still unsure whether your points are being covered. your points are vague without concrete references to the code. can you please help me help you?

> I'm always reluctant to add things back to an open source repo since my
> java formatter may not agree with the existing format

why should just adding `@Override` or fixing name shadowing cause format issues? if there are issues because of formatting (which i am flexible about), i would comment in the PR. what is the big deal? i guess your group is using steve or building something on top of steve... why not being a little bit cooperative here in this OSS world? which brings me to my next point about the following sentence:

> My group has very strict rules about java warnings & safety, based on past problems.

considering my arguments above and your general reluctance of guiding or helping me, why should _this_ project even care about _your_ group's rules then? i, as the only developer of this project, did and do not have any problems.

**Comment by evanbross** [comment]
I've disabled my auto-code formatter and have pulled a clean clone of the
project.
I added a few of the missing @Override annotations.
Is it ok to push to master or should I be creating a branch. I've observed
that some projects like to do it one way, some the other.

**Comment by goekay** [comment]
> Is it ok to push to master or should I be creating a branch.

you will not be able to push to steve's master due to missing permissions.

"how to"s:
- https://gist.github.com/Chaser324/ce0505fbed06b947d962
- https://guides.github.com/introduction/flow/

**Comment by goekay** [comment]
closing this issue due to its inactivity.
