### ISSUE TITLE
integreting SETEC charging station to bakend

### ISSUE THREAD

**Issue by eyalmanor** [RWTH-i5-IDSG/steve#689]
#### Checklist

- [ ] I checked other issues already, but found no answer/solution
- [ ] I checked the documentation and wiki, but found no answer/solution
- [ ] I am running the latest version and the issue still occurs
- [ ] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.4.5
Operating system  : ubuntu
JDK               : 11.0.11
Database          : 8

#### Expected Behavior
SETEC vendor charging station connect to the bakend
...

#### Actual Behavior
the log:
[WARN ] 2021-10-27 13:56:59,398 org.springframework.web.servlet.PageNotFound - No mapping for GET /steve/websocket/CentralSystemService/4/CBI-1625302527208
[WARN ] 2021-10-27 13:57:02,669 org.springframework.web.servlet.PageNotFound - No mapping for GET /steve/websocket/CentralSystemService/4/CBI-1625302527208
[WARN ] 2021-10-27 13:57:05,955 org.springframework.web.servlet.PageNotFound - No mapping for GET /steve/websocket/CentralSystemService/4/CBI-1625302527208
[WARN ] 2021-10-27 13:57:09,210 org.springframework.web.servlet.PageNotFound - No mapping for GET /steve/websocket/CentralSystemService/4/CBI-1625302527208
...

#### Steps to Reproduce the Problem
the charging station wont connect to steve 
  1. ...
  2. ...
  3. ...


#### Additional context

...

**Comment by goekay** [comment]
hey @eyalmanor sorry for the really late reply. either what @csamsel said, or.... i think you might have found an edge case:

is my assumption correct that you are using the character `/` within the chargebox id? steve considers the chargebox id to be the postfix after the last `/`. this would be `CBI-1625302527208`  from the URL `/steve/websocket/CentralSystemService/4/CBI-1625302527208` . and this value is not in your database since you must have inserted the intended value `4/CBI-1625302527208`.

i am unsure what the spec says about having  `/` within the chargeboxid. anyways, i will relax the condition when extracting the chargebox id from the json/ws url.
