### ISSUE TITLE
Separate bind address and publish address in conifg

### ISSUE THREAD

**Issue by ue-lee** [RWTH-i5-IDSG/steve#723]
### Problem
If I put SteVe behind a reverse-proxy I can set "server.host" to 0.0.0.0 or the internal IP. But in Web interface "About" also the internal IP will be shown and not the publish ip or hostname.

### Solution
Introduce separate config parameters for bind address (=internal) and publish address/hostname (=external access).

**Comment by goekay** [comment]
i actually think this behavior is okay.

steve tries to detect all IPs it can find [using different strategies](https://github.com/RWTH-i5-IDSG/steve/blob/beb746dc4dd58eabd557584ff7f13e30f62a883e/src/main/java/de/rwth/idsg/steve/JettyServer.java#L249) to help the user of steve figure out the IP. this small feature is designed to provide a superset of all possibilities, and not to detect the exact IP. because of this, it is an assistant which needs human supervision.
