### ISSUE TITLE
StopTransaction : new connector is created with the id of the transaction

### ISSUE THREAD

**Issue by andresxz32** [RWTH-i5-IDSG/steve#742]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [ ] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.4.8
JDK               : 15
Database          : MariaDB
```

#### Steps to Reproduce the Problem

1. New connector is created with the id of the transaction
  1.1 Clone [Simulator OCPP1.6](https://github.com/elifTech/cpd-ocpp), open examples, modify line 59 [](https://github.com/elifTech/cpd-ocpp/blob/969d124a8c6f87d67f854246be1356fe11afe927/examples/chargingPoint.js#L59) by idTag = "root". Modify [Simulator OCPP1.6](https://github.com/elifTech/cpd-ocpp/blob/969d124a8c6f87d67f854246be1356fe11afe927/examples/chargingPoint.js#L18) by CP9106 and create new charger point with ChargerBoxId = CP9106
  1.2. Run charginPoint.js
  1.3. In Steve central system create a new Ocpp tag
![image](https://user-images.githubusercontent.com/70045458/150012659-8efcf1ec-b93c-4b8c-b95d-767f78b3a061.png)
 1.4. StartTransaction and StopTransaction in my Case repeat 3 times and the nexts transaction create new connector with "connectorId" = "transactionID"

2. I Need create a socket for emit all users when charging points change. Where would be the best option to do it?

**Comment by goekay** [comment]
i don't think this is a problem with steve.

the project you referenced has this line: 

https://github.com/elifTech/cpd-ocpp/blob/969d124a8c6f87d67f854246be1356fe11afe927/examples/chargingPoint.js#L86

so, in the StatusNotification it uses the transactionId as the connectorId. this is wrong.

here is what happens in steve when this message arrives: 
1) let's look whether we know this connectorId
2a) known: store the status information for this connectorId
2b) unknown: register the connectorId first, store the status information later.

because of the wrong setting in chargingPoint.js, steve executes 1 and then 2b.
