### ISSUE TITLE
Sex not required

### ISSUE THREAD

**Issue by TechOverflow** [RWTH-i5-IDSG/steve#80]
I just noticed that this user field is required and I think it may be better as optional. Is there a file where this can easily be changed?

**Comment by goekay** [comment]
no. since this field consists of a drop down menu, you have to select something. i could add something like `-- Empty --` to this drop down list to express that it is optional as it the case in some other drop down menus. but then again, the drop down menu already contains `Other` which could be used to achive the same. i fail to see that this really is a problem.

**Comment by goekay** [comment]
we already print the endpoint address of a station in its charge point details page.

**Comment by TechOverflow** [comment]
I mean the server endpoints, which are shown in terminal when the app is started.

**Comment by goekay** [comment]
okay, we can display them on the about page of steve. i will look into it.

**Comment by goekay** [comment]
> Is it possible to echo out the endpoints in the web interface?

this is implemented in commit 27323aa484893495c273295027eef745dc2648e2. i am closing this issue, since i consider it resolved.
