### ISSUE TITLE
ENUM values for meter values

### ISSUE THREAD

**Issue by eviontech** [RWTH-i5-IDSG/steve#868]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [ ] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : ...
Operating system  : ...
JDK               : ...
Database          : ...
```

#### Expected Behavior

Is there any way to add celcius to this ENUM claass ?
#### Actual Behavior

 Cannot deserialize value of type `ocpp.cs._2015._10.UnitOfMeasure` from String "Celcius": not one of the values accepted for Enum class: [A, Percent, var, K, kW, Wh, Fahrenheit, W, kvar, Celsius, varh, VA, kvarh, V, kWh, kVA]

#### Additional context

...

**Comment by goekay** [comment]
the station sends the unit with a typo: Celcius instead of Celsius. the station should be fixed. every work around will be a hack.

that being said, these enum values come from https://github.com/RWTH-i5-IDSG/ocpp-jaxb/tree/master/src/main/resources/wsdl.

you can modify the files, bump the version number of the project, build and install it locally via maven. afterwards, you can reference (and therefore use) this version in steve: https://github.com/RWTH-i5-IDSG/steve/blob/master/pom.xml#L485
