### ISSUE TITLE
User ID tag is truncated

### ISSUE THREAD

**Issue by 164747** [RWTH-i5-IDSG/steve#9]
Go DataManagement -> Users

Create user with tag 12345678901234567890

Final user tag is now: 123456789012345

**Comment by goekay** [comment]
this is due to the defined max length in the initial schema of the idTag which is 15. so mysql does not raise an exception but trancates the "extra characters" and stores it like that. please check your database modes, and use a more strict mode: http://dev.mysql.com/doc/refman/5.6/en/sql-mode.html

on the other hand, i will fix the schema with the next migration script by setting the max length of all varchar fields to 255.
